name: Docker Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        # ！！！！！！！！！！！！！！！！！！！！！！
        # ↓↓↓ 把这里的 your-dockerhub-username 改成你自己的！ ↓↓↓
        tags: your-dockerhub-username/phala-card-checker:linxia112
        # ↑↑↑ 把这里的 your-dockerhub-username 改成你自己的！ ↑↑↑
        # ！！！！！！！！！！！！！！！！！！！！！！
